[package]
name = "designal"
version = "0.1.0"
authors = ["Paul Dorehill"]
edition = "2018"
description = "Procedural macro for use with futures-signals"
license = "MIT"
repository = "https://github.com/pauldorehill/designal"

[dependencies]
proc-macro2 = "1.0"
syn = "1.0"
quote = "1.0"

[dev-dependencies]
futures-signals = "0.3"
trybuild = "1.0"

[lib]
proc-macro = true