[package]
name = "designal"
version = "0.3.2"
authors = ["Paul Dorehill"]
edition = "2018"
description = "Procedural macro for use with futures-signals"
license = "MIT"
repository = "https://github.com/pauldorehill/designal"
keywords = ["futures-signals", "mutable", "signals"]
categories = ["data-structures"]

[dependencies]
proc-macro2 = "1.0"
syn = { version = "1.0", features = ["parsing", "derive"] }
# syn = { version = "1.0", features = ["extra-traits"] }
quote = "1.0"

[dev-dependencies]
futures-signals = "0.3"
trybuild = "1.0"

[lib]
proc-macro = true